---
- name: "set hostname according to inventory"
  hostname:
    name: "{{ inventory_hostname }}"
  tags:
    - hosts-configure

- name: "bind hosts to their private IPs"
  template:
    src:   "etc/hosts.j2"
    dest:  "/etc/hosts"
    mode:  0644
    owner: root
    group: root
  tags:
    - hosts-configure
